repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pylama
        name: pylama
        entry: poetry run pylama
        language: system
        types: [python]
