name: Docker and Pytest Workflow

on:
  push:
    branches: [ dev2, main ]
  pull_request:
    branches: [ dev2, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t fastapi-template:amd .
    - name: Run Pytest in /src directory
      run: docker run --rm fastapi-template:amd /bin/sh -c "cd src && mkdir logs && poetry run python -m pytest ."


