name: Docker and Pytest Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t fastapi-template:amd .
    - name: Run Pytest
      run: docker run --rm fastapi-template:amd /bin/bash -c "cd src && poetry run python -m pytest ."

